query getAuthSsoRedirect {
  redirect: authSsoRedirect {
    url
    state
  }
}

query getAuthToken($token: String!) {
  authToken(token: $token) {
    ...AuthToken
  }
}

fragment AuthToken on AuthToken {
  expiresAt
  token
  user {
    permissions
  }
}
